Repository lablup/backend.ai-client-py, pull requests merged in 2020-08, with the labels that each got.

#120 fix: replace api_session which only exists in master branch
  src/ai/backend/client/domain.py
  src/ai/backend/client/group.py
  src/ai/backend/client/user.py
Labels: bug

#121 fix: API v4/v5 compatibility issues
  changes/121.fix
  src/ai/backend/client/cli/admin/sessions.py
  src/ai/backend/client/cli/pretty.py
  src/ai/backend/client/func/session.py
Labels: bot:chronographer:provided

#119 fix: user_id filter is missing in paginated keypair list
  changes/119.fix
  src/ai/backend/client/func/keypair.py
Labels: bot:chronographer:provided, bug

#122 feat: display full_name when querying keypair(s)
  changes/122.feature
  src/ai/backend/client/cli/admin/keypairs.py
Labels: bot:chronographer:provided, enhancement
