Repository lablup/backend.ai-client-py, pull requests merged in 2020-04, with the labels that each got.

#95 repo: Adopt towncrier for changelog management
  CHANGELOG.md
  HISTORY.rst
  changes/0.breaking
  changes/0.feature
  changes/77.feature
  changes/79.feature
  changes/80.feature
  changes/82.breaking
  changes/82.feature
  changes/85.feature
  changes/90.fix
  changes/94.fix
  changes/95.misc
  changes/template.md
  pyproject.toml
  setup.py
Labels: bot:chronographer:provided

#97 Adaptation for API v5 revisions (Phase 1)
  .github/workflows/lint-flake8.yml
  .github/workflows/typecheck-mypy.yml
  .travis.yml
  appveyor.yml
  changes/97.breaking
  changes/97.feature
  setup.cfg
  setup.py
  src/ai/backend/client/cli/admin/images.py
  src/ai/backend/client/cli/app.py
  src/ai/backend/client/cli/proxy.py
  src/ai/backend/client/cli/run.py
  src/ai/backend/client/compat.py
  src/ai/backend/client/config.py
  src/ai/backend/client/etcd.py
  src/ai/backend/client/func/admin.py
  src/ai/backend/client/func/agent.py
  src/ai/backend/client/func/auth.py
  src/ai/backend/client/func/base.py
  src/ai/backend/client/func/bgtask.py
  src/ai/backend/client/func/domain.py
  src/ai/backend/client/func/dotfile.py
  src/ai/backend/client/func/etcd.py
  src/ai/backend/client/func/group.py
  src/ai/backend/client/func/image.py
  src/ai/backend/client/func/keypair.py
  src/ai/backend/client/func/keypair_resource_policy.py
  src/ai/backend/client/func/manager.py
  src/ai/backend/client/func/resource.py
  src/ai/backend/client/func/scaling_group.py
  src/ai/backend/client/func/session.py
  src/ai/backend/client/func/session_template.py
  src/ai/backend/client/func/system.py
  src/ai/backend/client/func/user.py
  src/ai/backend/client/func/vfolder.py
  src/ai/backend/client/py.typed
  src/ai/backend/client/request.py
  src/ai/backend/client/session.py
  src/ai/backend/client/test_utils.py
  src/ai/backend/client/types.py
  src/ai/backend/client/utils.py
  src/ai/backend/client/versioning.py
  tests/cli/test_cli_proxy.py
  tests/test_kernel.py
  tests/test_request.py
Labels: bot:chronographer:provided

#98 fix: server's error detail is not displayed
  src/ai/backend/client/cli/pretty.py
Labels: bug

#99 feat: add command to rename a file/directory inside a vfolder
  changes/99.feature
  src/ai/backend/client/cli/vfolder.py
  src/ai/backend/client/func/vfolder.py
Labels: bot:chronographer:provided, enhancement

#100 Improve console-server support
  changes/100.feature
  setup.cfg
  src/ai/backend/client/auth.py
  src/ai/backend/client/request.py
  src/ai/backend/client/session.py
  tests/test_auth.py
Labels: bot:chronographer:provided

#96 feat: add usage_mode and permission option in creating vfolder
  changes/96.feature
  src/ai/backend/client/cli/vfolder.py
  src/ai/backend/client/func/vfolder.py
Labels: bot:chronographer:provided, enhancement

#101 feat: add server log list command
  changes/101.feature
  src/ai/backend/client/cli/__init__.py
  src/ai/backend/client/cli/server_log.py
  src/ai/backend/client/func/server_log.py
  src/ai/backend/client/request.py
  src/ai/backend/client/session.py
Labels: bot:chronographer:provided, enhancement
