Repository lablup/backend.ai-client-py, pull requests merged in 2020-10, with the labels that each got.

#128 refactor: remove no longer needed session argument (https://github.com/lablup/backend.ai/issues/214)
  changes/128.breaking
  src/ai/backend/client/cli/admin/license.py
  src/ai/backend/client/cli/app.py
  src/ai/backend/client/cli/proxy.py
  src/ai/backend/client/func/admin.py
  src/ai/backend/client/func/agent.py
  src/ai/backend/client/func/auth.py
  src/ai/backend/client/func/bgtask.py
  src/ai/backend/client/func/domain.py
  src/ai/backend/client/func/dotfile.py
  src/ai/backend/client/func/etcd.py
  src/ai/backend/client/func/group.py
  src/ai/backend/client/func/image.py
  src/ai/backend/client/func/keypair.py
  src/ai/backend/client/func/keypair_resource_policy.py
  src/ai/backend/client/func/manager.py
  src/ai/backend/client/func/resource.py
  src/ai/backend/client/func/scaling_group.py
  src/ai/backend/client/func/server_log.py
  src/ai/backend/client/func/session.py
  src/ai/backend/client/func/session_template.py
  src/ai/backend/client/func/system.py
  src/ai/backend/client/func/user.py
  src/ai/backend/client/func/vfolder.py
  src/ai/backend/client/pagination.py
  src/ai/backend/client/request.py
  tests/integration/test_auth.py
  tests/integration/test_request.py
  tests/test_asyncio_kernel.py
  tests/test_kernel.py
  tests/test_request.py
  tests/test_vfolder_tus.py
Labels: bot:chronographer:provided

#127 Support vfolder clone
  changes/127.feature
  src/ai/backend/client/cli/vfolder.py
  src/ai/backend/client/func/vfolder.py
  tests/test_vfolder.py
Labels: bot:chronographer:provided, enhancement

#130 feature: additional arguments to support xfs
  changes/130.feature
  src/ai/backend/client/cli/utils.py
  src/ai/backend/client/cli/vfolder.py
  src/ai/backend/client/func/vfolder.py
Labels: bot:chronographer:provided, enhancement

#133 fix: Follow-up fixes for #127
  changes/133.fix
  src/ai/backend/client/cli/vfolder.py
  src/ai/backend/client/func/vfolder.py
Labels: bot:chronographer:provided, refactor

#135 fix: More details in "vfolder list" command
  changes/135.fix
  src/ai/backend/client/cli/vfolder.py
Labels: bot:chronographer:provided, enhancement

#136 fix: More helpful error messages with invalid API params
  changes/136.fix
  src/ai/backend/client/cli/pretty.py
Labels: bot:chronographer:provided, bug

#137 fix: Naming/defaults of new vfolder args
  changes/137.fix
  src/ai/backend/client/cli/vfolder.py
  src/ai/backend/client/func/vfolder.py
Labels: bot:chronographer:provided, bug

#139 fix: wrong argument name of vfolder update-options command
  changes/139.fix
  src/ai/backend/client/cli/vfolder.py
Labels: bot:chronographer:provided, bug

#140 fix: Regression in "admin vfolders" command
  changes/140.fix
  src/ai/backend/client/cli/admin/vfolders.py
  src/ai/backend/client/func/vfolder.py
Labels: bot:chronographer:provided, bug

#142 setup: Update dependencies (aiohttp 3.7)
  .github/workflows/lint-flake8.yml
  .github/workflows/lint-towncrier.yml
  .github/workflows/test-pytest.yml
  .github/workflows/typecheck-mypy.yml
  changes/142.misc
  requirements/build.txt
  setup.py
Labels: enhancement

#138 backend.ai ssh/scp commands
  changes/138.feature
  src/ai/backend/client/cli/__init__.py
  src/ai/backend/client/cli/ssh.py
Labels: bot:chronographer:provided, cli, client, feature, usability

#143 setup: Update deps (aiohttp 3.7.2, mypy 0.790)
  changes/143.fix
  setup.py
Labels: enhancement
