Repository lablup/backend.ai-client-py, pull requests merged in 2020-07, with the labels that each got.

#109 feat: add --starts-at option for creating session
  changes/109.feature
  src/ai/backend/client/cli/run.py
  src/ai/backend/client/func/session.py
Labels: bot:chronographer:provided, enhancement

#110 Support scheduler operation API
  changes/110.feature
  src/ai/backend/client/cli/manager.py
  src/ai/backend/client/func/manager.py
Labels: bot:chronographer:provided

#111 refactor: replace user's is_active field into status
  changes/111.breaking
  src/ai/backend/client/cli/admin/users.py
  src/ai/backend/client/func/user.py
Labels: bot:chronographer:provided, refactor

#113 fix: change user_id's type from str to UUID
  changes/113.fix
  src/ai/backend/client/func/user.py
Labels: bot:chronographer:provided, refactor

#114 feat(cli.run): Add support for user bootstrap script
  changes/114.feature
  src/ai/backend/client/cli/run.py
Labels: bot:chronographer:provided

#116 fix: Show the unique session ID correctly after creating sessions
  changes/116.fix
  src/ai/backend/client/cli/pretty.py
  src/ai/backend/client/cli/run.py
  src/ai/backend/client/func/session.py
Labels: bot:chronographer:provided

#117 feat: purge command for users, groups, and domains
  changes/117.feature
  src/ai/backend/client/cli/admin/domains.py
  src/ai/backend/client/cli/admin/groups.py
  src/ai/backend/client/cli/admin/users.py
  src/ai/backend/client/func/domain.py
  src/ai/backend/client/func/group.py
  src/ai/backend/client/func/user.py
Labels: bot:chronographer:provided, enhancement
