Repository lablup/backend.ai-client-py, pull requests merged in 2021-05, with the labels that each got.

#160 fix: change ScalingGroupInput to CreateScalingGroupInput which was changed last month
  changes/160.fix
  src/ai/backend/client/func/scaling_group.py
Labels: bug

#159 feat: add command to share/unshare group virtual folders to users
  changes/159.feature
  src/ai/backend/client/cli/vfolder.py
  src/ai/backend/client/func/vfolder.py
Labels: feature

#161 feat: Add support for SCHEDULED status
  changes/161.feature
  src/ai/backend/client/cli/admin/sessions.py
  src/ai/backend/client/cli/ps.py
  src/ai/backend/client/cli/run.py
Labels: enhancement
